services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
      - "0.0.0.0:4567:4567"
    volumes:
      - ./static:/var/www/html:ro
    depends_on:
      - gawk
    environment:
      - AWKBLOG_PORT=80
      - PORT=4567
      - AWKBLOG_INTERNAL_HOSTNAME=gawk
  gawk:
    build:
      dockerfile: ./docker/default/Dockerfile
      context: ./
    depends_on:
      - db
    volumes:
      - "./:/app"
    env_file:
      - .env
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DATABASE=postgres
      - PORT=80
      - ENCRYPTION_KEY=fvrcWCKkyxsmOkvmaxFLsrEXgrWqGrsh
      - DEBUG=1
  db:
    image: postgres:14
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
  oauth-mock:
    # https://github.com/yammerjp/github-oauth2-login-mock-server
    image: ghcr.io/yammerjp/github-oauth2-login-mock-server:latest
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
volumes:
  db-store:
