services:
  app:
    build:
      dockerfile: ./docker/with-nginx/Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "0.0.0.0:4567:4567"
    env_file:
      - .env
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DATABASE=postgres
      - PORT=4567
      - AWKBLOG_PORT=4568
      - AWKBLOG_INTERNAL_HOSTNAME=127.0.0.1
      - ENCRYPTION_KEY=fvrcWCKkyxsmOkvmaxFLsrEXgrWqGrsh
      - PRIVATE_BEARER_TOKEN=d02ff6f3cfc03d7ba39ad7eb9044e60676404192
  db:
    image: postgres:14
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
  oauth-mock:
    # https://github.com/yammerjp/github-oauth2-login-mock-server
    image: ghcr.io/yammerjp/github-oauth2-login-mock-server:latest
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
volumes:
  db-store:
