services:
  gawk:
    build: ./
    entrypoint: /app/start.sh
    depends_on:
      - db
    volumes:
      - "./:/app"
    ports:
      - "4567:4567"
    env_file:
      - .env
      - .env_postgres
  db:
    image: postgres:14
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file:
      - .env_postgres
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:4568:80"
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: yammer@example.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
volumes:
  db-store:
  pgadmin4_data:
