services:
  gawk:
    build: ./
    depends_on:
      - db
    volumes:
      - "./:/app"
    ports:
      - "0.0.0.0:4567:4567"
    env_file:
      - .env
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DATABASE=postgres
      - PORT=4567
      - ENCRYPTION_KEY=fvrcWCKkyxsmOkvmaxFLsrEXgrWqGrsh
      - PRIVATE_BEARER_TOKEN=d02ff6f3cfc03d7ba39ad7eb9044e60676404192

  db:
    image: postgres:14
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:4568:80"
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: yammer@example.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
  oauth-mock:
    image: basd4g/github-oauth2-login-mock-server
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
volumes:
  db-store:
  pgadmin4_data:
