on:
  push:
    branches:
      - main

name: Docker Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/awkblog:latest \
          --tag ghcr.io/$GITHUB_ACTOR/awkblog:$(echo $GITHUB_SHA | head -c7) \
          -f docker/default/Dockerfile \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/awkblog:latest
          docker push ghcr.io/$GITHUB_ACTOR/awkblog:$(echo $GITHUB_SHA | head -c7)

      - name: Build Docker Image (includes nginx)
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/awkblog-with-nginx:latest \
          --tag ghcr.io/$GITHUB_ACTOR/awkblog-with-nginx:$(echo $GITHUB_SHA | head -c7) \
          -f docker/with-nginx/Dockerfile \
          .
      - name: Push Docker Image (includes nginx)
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/awkblog-with-nginx:latest
          docker push ghcr.io/$GITHUB_ACTOR/awkblog-with-nginx:$(echo $GITHUB_SHA | head -c7)
